CREATE DATABASE IF NOT EXISTS triset_documents CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE triset_documents;

CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('Admin','Accounts','HR','Staff') NOT NULL DEFAULT 'Staff', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_users_role (role));
CREATE TABLE IF NOT EXISTS company_settings (id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1, company_name VARCHAR(190) NOT NULL, address TEXT NOT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(40) NOT NULL, gstin VARCHAR(32), pan VARCHAR(32), cin VARCHAR(64), udyam VARCHAR(64), bank_name VARCHAR(190), account_name VARCHAR(190), account_number VARCHAR(64), ifsc VARCHAR(32), branch VARCHAR(190), logo_path VARCHAR(255), authorised_signatory VARCHAR(190), default_gst_rate DECIMAL(5,2) DEFAULT 18, invoice_prefix VARCHAR(32) DEFAULT 'INV-', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS clients (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, contact_person VARCHAR(190), address TEXT, city VARCHAR(100), state VARCHAR(100), state_code VARCHAR(8), gstin VARCHAR(32), pan VARCHAR(32), email VARCHAR(190), phone VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_clients_name (name), INDEX idx_clients_gstin (gstin));
CREATE TABLE IF NOT EXISTS employees (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, employee_id VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(190) NOT NULL, designation VARCHAR(150), department VARCHAR(150), date_of_joining DATE, gender VARCHAR(32), pan VARCHAR(32), uan VARCHAR(32), pf_number VARCHAR(64), esic_number VARCHAR(64), bank_name VARCHAR(190), account_number VARCHAR(64), branch VARCHAR(190), location VARCHAR(100), band_grade VARCHAR(64), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_employees_name (name), INDEX idx_employees_department (department));
CREATE TABLE IF NOT EXISTS service_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS services (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES service_categories(id) ON DELETE CASCADE, UNIQUE KEY uq_service_name (category_id, name));
CREATE TABLE IF NOT EXISTS quotations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quotation_number VARCHAR(64) NOT NULL UNIQUE, quotation_date DATE NOT NULL, valid_until DATE, client_id BIGINT UNSIGNED, reference VARCHAR(190), gst_type ENUM('IGST','CGST_SGST','NONE') DEFAULT 'NONE', gst_rate DECIMAL(5,2) DEFAULT 0, notes TEXT, payment_terms TEXT, delivery_terms TEXT, status ENUM('Draft','Generated','Converted') DEFAULT 'Draft', created_by BIGINT UNSIGNED, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_quotations_date (quotation_date), INDEX idx_quotations_status (status));
CREATE TABLE IF NOT EXISTS quotation_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quotation_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED, service_id BIGINT UNSIGNED, description TEXT NOT NULL, quantity DECIMAL(12,3) NOT NULL DEFAULT 1, unit VARCHAR(32), rate DECIMAL(14,2) NOT NULL DEFAULT 0, taxable_amount DECIMAL(14,2) NOT NULL DEFAULT 0, FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE, FOREIGN KEY (category_id) REFERENCES service_categories(id) ON DELETE SET NULL, FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS invoices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_number VARCHAR(64) NOT NULL UNIQUE, invoice_date DATE NOT NULL, invoice_type ENUM('DATA_ENTRY','DIGITAL_SOLUTIONS','PHOTOGRAMMETRY') NOT NULL, client_id BIGINT UNSIGNED, reference VARCHAR(190), po_date DATE, gst_type ENUM('IGST','CGST_SGST','NONE') DEFAULT 'NONE', gst_rate DECIMAL(5,2) DEFAULT 0, subtotal DECIMAL(14,2) DEFAULT 0, total_tax DECIMAL(14,2) DEFAULT 0, round_off DECIMAL(14,2) DEFAULT 0, grand_total DECIMAL(14,2) DEFAULT 0, amount_in_words TEXT, notes TEXT, terms TEXT, created_by BIGINT UNSIGNED, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_invoices_date (invoice_date), INDEX idx_invoices_type (invoice_type));
CREATE TABLE IF NOT EXISTS invoice_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, description TEXT NOT NULL, sac_hsn VARCHAR(64), quantity DECIMAL(12,3) NOT NULL DEFAULT 1, unit VARCHAR(32), rate DECIMAL(14,2) NOT NULL DEFAULT 0, taxable_value DECIMAL(14,2) NOT NULL DEFAULT 0, igst DECIMAL(14,2) DEFAULT 0, cgst DECIMAL(14,2) DEFAULT 0, sgst DECIMAL(14,2) DEFAULT 0, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS purchase_orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, po_number VARCHAR(64) NOT NULL UNIQUE, po_date DATE NOT NULL, vendor TEXT NOT NULL, ship_to TEXT, registered_office TEXT, gstin VARCHAR(32), pan VARCHAR(32), state VARCHAR(100), state_code VARCHAR(8), reference VARCHAR(190), vendor_code VARCHAR(64), subtotal DECIMAL(14,2) DEFAULT 0, total_tax DECIMAL(14,2) DEFAULT 0, total DECIMAL(14,2) DEFAULT 0, payment_terms TEXT, delivery_terms TEXT, taxes_duties TEXT, other_information TEXT, annexure JSON, created_by BIGINT UNSIGNED, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS purchase_order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, purchase_order_id BIGINT UNSIGNED NOT NULL, description TEXT NOT NULL, hsn_sac VARCHAR(64), quantity DECIMAL(12,3) DEFAULT 1, unit VARCHAR(32), rate DECIMAL(14,2) DEFAULT 0, taxable_amount DECIMAL(14,2) DEFAULT 0, gst DECIMAL(14,2) DEFAULT 0, FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS payslips (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, employee_id BIGINT UNSIGNED, template ENUM('CORPORATE','COMPACT') NOT NULL, pay_period DATE NOT NULL, data JSON NOT NULL, gross_earnings DECIMAL(14,2) DEFAULT 0, gross_deductions DECIMAL(14,2) DEFAULT 0, net_pay DECIMAL(14,2) DEFAULT 0, created_by BIGINT UNSIGNED, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_payslips_period (pay_period));
CREATE TABLE IF NOT EXISTS documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, document_type VARCHAR(64) NOT NULL, document_number VARCHAR(64) NOT NULL, category VARCHAR(100), client_id BIGINT UNSIGNED, employee_id BIGINT UNSIGNED, amount DECIMAL(14,2) DEFAULT 0, status VARCHAR(32) NOT NULL DEFAULT 'Draft', created_by BIGINT UNSIGNED, pdf_reference VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL, FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_documents_type (document_type), INDEX idx_documents_number (document_number), INDEX idx_documents_created (created_at));

INSERT INTO company_settings (id, company_name, address, email, phone) VALUES (1, 'TRISET Solutions India Private Limited', 'Flat No. 201, Plot No.851, Ramakrishnapuram, Pragatinagar, Hyderabad, Telangana, India - 500090', 'info@trisetsolutions.com', '7416612292') ON DUPLICATE KEY UPDATE company_name=VALUES(company_name);
